import 'package:flutter/material.dart';

const int APP_COLOR = 0xFF1414FA;
const int APP_COLOR_ACCENT = 0xFF1414FA;

const Map<int, Color> APP_SWATCH = {
  050: Color.fromRGBO(0x14, 0x14, 0xFA, 0.1),
  100: Color.fromRGBO(0x14, 0x14, 0xFA, 0.2),
  200: Color.fromRGBO(0x14, 0x14, 0xFA, 0.3),
  300: Color.fromRGBO(0x14, 0x14, 0xFA, 0.4),
  400: Color.fromRGBO(0x14, 0x14, 0xFA, 0.5),
  500: Color.fromRGBO(0x14, 0x14, 0xFA, 0.6),
  600: Color.fromRGBO(0x14, 0x14, 0xFA, 0.7),
  700: Color.fromRGBO(0x14, 0x14, 0xFA, 0.8),
  800: Color.fromRGBO(0x14, 0x14, 0xFA, 0.9),
  900: Color.fromRGBO(0x14, 0x14, 0xFA, 1.0),
};

const String APP_LOGO = 'assets/images/app_logo.png';
const String LOADING_GIF = 'assets/images/loading.gif';
const String ACCOUNT_PNG = 'assets/images/account.png';
const String RED_CROSS_PNG = 'assets/images/red_cross.png';

const String REQUIREMENTS = 'requirements';
const String TRANSACTIONS = 'transactions';
const String TOKENS = 'tokens';
const String USERS = 'users';

const String HELP_EMAIL = 'swarupanandadhua@gmail.com';
const String HELP_SUB = 'subject=FarmApp%20Help';
const String HELP_BODY = 'body=Please%20type%20your%20query%20here...';
const String HELP_MAIL_ARG = 'mailto:$HELP_EMAIL?$HELP_SUB&$HELP_BODY';

const List<String> PRODUCT_NAMES = [
  'আদা (Ginger)',
  'আলু (Potato)',
  'ওল (Elephant Foot Yam)',
  'ওলকপি (Kohlrabi)',
  'কচু (Arum)',
  'করলা (Balsam Apple)',
  'কলমি শাক (Bindweed)',
  'কলার মোচা (Plantain Flower)',
  'কাঁকরোল (Sweet Bitter Gourd)',
  'কাঁচা কলা (Green Banana)',
  'কাঁচা পেঁপে (Green Papaya)',
  'কাঁচা লংকা (Green Chili)',
  'কুন্দরি (Little Gourd)',
  'কুমড়া (Pumpkin)',
  'গাঁজর (Carrot)',
  'চালকুমড়া (Green Cucumber)',
  'চিচিংগা (Snake Gourd)',
  'ঝিংগে (Rige Gourd)',
  'টমেটো (Tomato)',
  'ঢেঁড়স (Lady’s Finger)',
  'ধনেপাতা (Coriander)',
  'ধুন্দুল (Zucchini)',
  'পটল (Pointed Gourd)',
  'পালং শাক (Spinach)',
  'পুঁই শাক (Basil)',
  'পুদিনা পাতা (Mint)',
  'পেয়ারা (Guava)',
  'পেঁয়াজ (Onion)',
  'পেঁয়াজ পাতা (Leek)',
  'ফুলকপি (Cauliflower)',
  'বরবটি (Asparagus Bean)',
  'বাঁধাকপি (Cabbage)',
  'বিন (Bean)',
  'বীট (Beet)',
  'বেগুন (Brinjal)',
  'ব্রোকলি (Broccoli)',
  'ভূট্টা (Maize)',
  'মটরশুঁটি (Green Pea)',
  'মাশরুম (Mushroom)',
  'মুলা (Radish)',
  'রসুন (Garlic)',
  'লম্বা বেগুন (Eggplant)',
  'লাউ (Bottle Gourd)',
  'লাল শাক (Read Leafy)',
  'লেটুসপাতা (Lettuce)',
  'লেবু (Lemon)',
  'শসা (Cucumber)',
  'শালগম (Turnip)',
  'শিম (Broad Bean)',
  'শিমলা মরিচ (Capsicum)',
  'সজনে (Drum Stick)',
  'হলুদ (Turmeric)',
  'হেলেঞ্চা শাক (Cress)',
];

const List<String> PRODUCT_IMAGES = [
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
  'assets/images/P013.jpg',
];
