const List<List<String>> PRODUCTS = [
  ['কচু', 'Arum', 'assets/images/arum.jpg'],
  ['করলা', 'Bitter Gourd', 'assets/images/bitter_gourd.jpg'],
  ['কাঁচা লংকা', 'Green Chili', 'assets/images/green_chili.jpg'],
  ['কুন্দরি', 'Coccinia', 'assets/images/coccinia.jpg'],
  ['কুমড়া', 'Pumpkin', 'assets/images/pumpkin.jpg'],
  ['ঝিংগে', 'Ridge Gourd', 'assets/images/ridge_gourd.jpg'],
  ['ঢেঁড়স', 'Ladies Finger', 'assets/images/ladies_finger.jpg'],
  ['পটল', 'Parwal', 'assets/images/parwal.jpg'],
  ['বরবটি', 'Bean - Cowpea', 'assets/images/bean_cowpea.jpg'],
  ['বেগুন', 'Brinjal', 'assets/images/brinjal.jpg'],
  ['লম্বা বেগুন', 'Eggplant', 'assets/images/eggplant.jpg'],
  ['লাউ', 'Bottle Gourd', 'assets/images/bottle_gourd.jpg'],
  ['শসা', 'Cucumber', 'assets/images/cucumber.jpg'],

  // WInter
  ['ওলকপি', 'Kohlrabi', 'assets/images/kohlrabi.jpg'],
  ['গাঁজর', 'Carrot', 'assets/images/carrot.jpg'],
  ['টমেটো', 'Tomato', 'assets/images/tomato.jpg'],
  ['ধনেপাতা', 'Coriander Leaves', 'assets/images/coriander_leaves.jpg'],
  ['পালং শাক', 'Spinach', 'assets/images/spinach.jpg'],
  ['ফুলকপি', 'Cauliflower', 'assets/images/cauliflower.jpg'],
  ['বাঁধাকপি', 'Cabbage', 'assets/images/cabbage.jpg'],
  ['বিন', 'Bean', 'assets/images/bean.jpg'],
  ['বীট', 'Beet', 'assets/images/beet.jpg'],
  ['মটরশুঁটি', 'Green Pea', 'assets/images/green_pea.jpg'],
  ['মুলা', 'Radish', 'assets/images/radish.jpg'],
  ['শিম', 'Broad Bean', 'assets/images/broad_bean.jpg'],
  ['ক্যাপসিকাম', 'Capsicum', 'assets/images/capsicum.jpg'],
  ['লাল ক্যাপসিকাম', 'Red Capsicum', 'assets/images/capsicum_red.jpg'],

  ['আদা', 'Ginger', 'assets/images/ginger.jpg'],
  ['রসুন', 'Garlic', 'assets/images/garlic.jpg'],
  ['পেঁয়াজ', 'Onion', 'assets/images/onion.jpg'],
  ['আলু', 'Potato', 'assets/images/potato.jpg'],

  ['হলুদ', 'Turmeric', 'assets/images/app_logo.jpg'],
  ['ওল', 'Elephant Foot Yam', 'assets/images/app_logo.jpg'],
  ['সজনে ডাঁটা', 'Drum Stick', 'assets/images/app_logo.jpg'],
  ['কলার মোচা', 'Banana Flower', 'assets/images/app_logo.jpg'],
  ['পেয়ারা', 'Guava', 'assets/images/guava.jpg'],
  ['কাঁচা কলা', 'Green Banana', 'assets/images/app_logo.jpg'],
  ['কাঁচা পেঁপে', 'Green Papaya', 'assets/images/app_logo.jpg'],
  ['ভূট্টা', 'Maize', 'assets/images/app_logo.jpg'],
  ['কাগজি লেবু', 'Lemon', 'assets/images/app_logo.jpg'],

  ['চালকুমড়া', 'Green Cucumber', 'assets/images/app_logo.jpg'],
  ['চিচিংগা', 'Snake Gourd', 'assets/images/app_logo.jpg'],
  ['ধুন্দুল', 'Zucchini', 'assets/images/app_logo.jpg'],
  ['ব্রোকলি', 'Broccoli', 'assets/images/broccoli.jpg'],
  ['মাশরুম', 'Mushroom', 'assets/images/app_logo.jpg'],
  ['শালগম', 'Turnip', 'assets/images/app_logo.jpg'],
  ['কাঁকরোল', 'Sweet Bitter Gourd', 'assets/images/sweet_bitter_gourd.jpg'],

  ['কলমি শাক', 'Bindweed', 'assets/images/app_logo.jpg'],
  ['পুঁই শাক', 'Basil', 'assets/images/app_logo.jpg'],
  ['পুদিনা পাতা', 'Mint', 'assets/images/app_logo.jpg'],
  ['পেঁয়াজ পাতা', 'Leek', 'assets/images/app_logo.jpg'],
  ['লাল শাক', 'Read Leafy', 'assets/images/app_logo.jpg'],
  ['লেটুসপাতা', 'Lettuce', 'assets/images/app_logo.jpg'],
  ['হেলেঞ্চা শাক', 'Cress', 'assets/images/app_logo.jpg'],
];
