const String STRING_APP_NAME = 'FarmApp';
const String STRING_CANCEL = 'Cancel';
const String STRING_ENTER_MOBILE_NUMBER = 'Enter Mobile Number';
const String STRING_ENTER_OTP = 'Enter the OTP';
const String STRING_ENTER_PIN_CODE = 'Enter Pin Code';
const String STRING_ENTER_PRICE_PER_KG = 'Enter price/kg';
const String STRING_ENTER_QUANTITY = 'Enter quantity (in kg)';
const String STRING_ENTER_YOUR_NAME = 'Enter your name';
const String STRING_FEEDBACK = 'Feedback';
const String STRING_HELP = 'Help';
const String STRING_HELP_BODY = 'body=Please%20type%20your%20query%20here...';
const String STRING_HELP_SUB = 'subject=FarmApp%20Help';
const String STRING_HISTORY = 'History';
const String STRING_HOME = 'Home';
const String STRING_KYC = 'KYC';
const String STRING_MOBILE = 'Mobile';
const String STRING_NAME = 'Name';
const String STRING_OTP_MUST_6_DIGITS = 'OTP must be 6 digits';
const String STRING_PERSONAL_INFORMATION = 'Personal Information';
const String STRING_PROCEED = 'PROCEED';
const String STRING_PROFILE = 'Profile';
const String STRING_PROFILE_UPDATE = 'Profile Update';
const String STRING_SAVE = 'Save';
const String STRING_SEND_OTP = 'Send OTP';
const String STRING_SETTINGS = 'Settings';
const String STRING_SIGN_OUT = 'Sign Out';
const String STRING_TRADE = 'Trade';
const String STRING_WELCOME_USER = 'Welcome User';
